### ISSUE TITLE
Ring stacks sometimes behave erratically when pairing with a new ring

### ISSUE THREAD

**Issue by ddoak** [UoA-eResearch/prx_fishtank#37]
Reproduction:
Play around with simulation and watch the behaviour of stacks when another ring approaches to pair.

Most visible with a long stack - sometimes it looks as though the entire stack is rotating *away* from the joining ring.

**Comment by neon-ninja** [comment]
I think the collider on the new ring might be pushing the stack away as it rubs against it when it comes in at a certain angle

**Comment by neon-ninja** [comment]
Something like my RingRepel function might help with this - rings pushing each other away a little but until they're in the right angle for pairing

**Comment by neon-ninja** [comment]
I also see this when holding a stack and aiming it at another stack - the other stack gets into the correct rotation which appears to be aiming away from the stack I'm holding due to the mismatched position
