### ISSUE TITLE
Interrupted stacks remain manipulable while attached.

### ISSUE THREAD

**Issue by ddoak** [UoA-eResearch/prx_fishtank#38]
Repro:
Pick up a stack and pull out a ring from the middle. 
Rings beyond the interrupted position remain attached to the original stack.

Desired behaviour is that the original stack should break (into two stacks) at the interruption.

**Comment by neon-ninja** [comment]
Do you mean the other part of the stack stays bound to the other hand while you're holding it? Or that the stacks float together and rebond?

**Comment by neon-ninja** [comment]
When you grab a ring in the middle of the stack, should the stack break in two such that you're holding two stacks? Or world you still only be holding one ring and the orphaned stack floats free?

**Comment by ddoak** [comment]
Good point - there are really two issues.

At the moment you can pull single ring out from the middle of a stack. This is fun - but creates the problem described above.

I think the most sensible and general solution is that the second hand attaching to a stack creates the opportunity to break it into two stacks at that position. The two 'new' stacks would then be attached one to each hand. 

This solution would mean that pulling out a single ring would not be possible. 

Although if it could be somehow maintained as a power user trick that would be fun! i.e. a rapid jerk at right angles to the stack axis allows one ring to be slipped out and the remaining split stack naturally closes up behind. Like pulling a tablecloth out from under plates ;)

**Comment by warrickct** [comment]
* Donor and acceptor positions are compared to the first attached hand 
* Attach all rings starting with the ring directly grabbed in the direction (donor or acceptor) furthest from the already attached hand to the second hand to grab hold.
