### ISSUE TITLE
Add more keyboard controls for demos (MOTAT feedback)

### ISSUE THREAD

**Issue by ddoak** [UoA-eResearch/prx_fishtank#40]
From watching MOTAT it is clear that keyboard controls for the demo-er would be useful.

Add more keyboard controls for guided demos.

Scale (adjustable up/down)
cartoon / surface rendering toggle
serious / party 

position reset i.e. predefined teleport to just outside tank

autoconfetti (reward (for little kids who are not going to make the tube on a reasonable timeframe but will leave happily if they get the confetti)

**Comment by ddoak** [comment]
Note: Controls pH / scale / render (sliders etc) are now attached to motion controller and the 'menu mode' system makes them active / non-active.

**Comment by warrickct** [comment]
Added menu cycling and value changing via keyboard arrow keys in 49e76d5395c93908ce367532b218abceb7a7f39e.
