### ISSUE TITLE
ring shader - switch from vertex shaded to and from transparent rendering is instantaneous

### ISSUE THREAD

**Issue by ddoak** [UoA-eResearch/prx_fishtank#46]
Stacks of three rings generate electric / nanowire particle fx - simultaneously the rings switch to a transparent shader so that the nanowire is visible

The current transition looks jarring (it is immediate) and would be much better if this was gradual (to and from)

However, this probably needs a shader which supports transparent vertex colours
Note that the current transparent shader is legacy - but is less costly than the default shader

**Comment by warrickct** [comment]
Closed in d1a173239db01b39281a5f90ce8ae2ccc52dbe47 Created a new shader that supports alpha transitioning and vertex colours. Transition speed is also editable in the prefab inspector if it needs to be changed.
