### ISSUE TITLE
Zipped 1.6.0 release build has incorrect data folder name 

### ISSUE THREAD

**Issue by ddoak** [UoA-eResearch/prx_fishtank#54]
Data folder in build is named "SteamVR_Data", should be  "prx_fishtank.v.1.6.0_Data"

(I think the Data folder defaults to the original project name - so if you change the exe name the folder name needs changing too)

In ZIP =

![01prx1 6 0](https://user-images.githubusercontent.com/7423291/47805081-5808b580-dd2e-11e8-884b-44997ab6e540.PNG)

FIXED = 

![02prx1 6 0](https://user-images.githubusercontent.com/7423291/47805090-5b03a600-dd2e-11e8-9dff-36865f6563a4.PNG)

**Comment by warrickct** [comment]
Thanks for submitting the bug. I've updated the 1.6.0 release so that the data folder name is based off the application name.
